language: c

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python3

script:
- make all CFLAGS='-ftest-coverage -fprofile-arcs -Wall' LDFLAGS='-ftest-coverage -fprofile-arcs' CC='gcc -std=gnu11'
- make bspcomp/bspcomp CFLAGS=''
- make coverage && cat Coverage.txt
