language: c

dist: xenial

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python3

script:
- make all CFLAGS='-ftest-coverage -fprofile-arcs -Wall' LDFLAGS='-ftest-coverage -fprofile-arcs' CC='gcc -std=gnu11'
- make bspcomp/bspcomp CFLAGS=''
- make check

after_success:
- bash <(curl -s https://codecov.io/bash)
