name: Test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install Python
      run: sudo apt-get update -qq && sudo apt-get install -qq python3
    - name: Build C-BSP
      run: make all CFLAGS='-ftest-coverage -fprofile-arcs -Wall' LDFLAGS='-ftest-coverage -fprofile-arcs' CC='gcc -std=gnu11'
    - name: Build bspcomp
      run: make bspcomp/bspcomp CFLAGS=''
    - name: Run tests
      run: make check
    - name: Upload coverage report to codecov.io
      uses: codecov/codecov-action@v1
